# testing Workflow

name: CI

# Control when thr workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allow you to run this workflow manually from action tab
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniconda-version: 'latest'
        python-version: 3.9

    - name: Create environment
      run: conda create -n myenv python=3.9

    - name: Init Conda
      run: conda init bash

      
    - name: Activate environment
      run: conda activate myenv

    - name: Verify Python version
      run: python --version
